### ISSUE TITLE
Incorrect  input image shape  in network forward pass

### ISSUE THREAD

**Issue by GrumpyZhou** [filipradenovic/cnnimageretrieval#2]
Hi,
I am using your code and my environment is:  
- ubuntu 16.04 
- matlab R2017b 
- matconvnet 1.0-beta25 compiled with option _'enableGpu'_ and _'cudaRoot'_ is CUDA-8.0.  

I got following error message when executing script  **test_cnnimageretrieval.m** (with use_gpu=1)

```
>> run test_cnnimageretrieval.m
>> retrievalSfM30k-siamac-vgg: Evaluating CNN image retrieval...
>> whitening: Extracting CNN descriptors for training images...
>>>> [  0.00%] [          ] [t ?] [e 0.0s] [r ?] Error using vl_nnnormalizelp
DATA and DEROUTPUT do not have the same size.

Error in L2N/forward (line 8)
      outputs{1} = vl_nnnormalizelp(inputs{1}, [], 'p', 2, 'epsilon', 1e-6) ;

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 91)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in cnn_vec (line 38)
        net.eval({'input', gpuarrayfun(reshape(im, [size(im), 1]))});

Error in test_cnnimageretrieval>@(x,y)cnn_vec(x,y)

Error in test_cnnimageretrieval (line 75)
        vecs_whiten{i} = descfun(imresizemaxd(imread(cid2filename(cids{i}, ims_whiten_dir)), test_imdim, 0), net);

```  

Then I notice in **cnn_vec.m** line 38  
`net.eval({'input', gpuarrayfun(reshape(im, [size(im), 1]))});`. It seems you want to expand the last dimension of im. However,  ` reshape(im, [size(im), 1]) ` won't change the shape of it.  Or I misunderstood your code?  

So I tried to change ` [size(im), 1] ` to `[1, size(im)]` as `vl_nnnormalizelp(inputs{1}, [], 'p', 2, 'epsilon', 1e-6) ;` takes the first batch. But soon I get another  error:  
```
>>>> [  0.00%] [          ] [t ?] [e 0.0s] [r ?] Error using vl_nnconv
The FILTERS depth does not divide the DATA depth.

Error in dagnn.Conv/forward (line 11)
      outputs{1} = vl_nnconv(...

Error in dagnn.Layer/forwardAdvanced (line 85)
      outputs = obj.forward(inputs, {net.params(par).value}) ;

Error in dagnn.DagNN/eval (line 91)
  obj.layers(l).block.forwardAdvanced(obj.layers(l)) ;

Error in cnn_vec (line 38)
        net.eval({'input', gpuarrayfun(reshape(im, [1, size(im)]))});

Error in test_cnnimageretrieval>@(x,y)cnn_vec(x,y)

Error in test_cnnimageretrieval (line 75)
        vecs_whiten{i} = descfun(imresizemaxd(imread(cid2filename(cids{i}, ims_whiten_dir)), test_imdim, 0), net);
```  

Do you have any idea how to solve this? I would be grateful !! THANKS!!!!!!

**Comment by filipradenovic** [comment]
The problem is caused by a non-matching MatConvNet library. Namely, you compiled matconvnet-1.0-beta25, however, our code is compatible with matconvnet-1.0-beta24. In the newest (beta25) version, developers of MatConvNet made a mex implementation of "vl_nnnormalizelp.m" function used in our library in "L2N.m", and its use is different during a forward pass now. A simple fix to make it work for beta25 is replacing a line 8 in "L2N.m", which is now:
`outputs{1} = vl_nnnormalizelp(inputs{1}, [], 'p', 2, 'epsilon', 1e-6) ;`
 with the following code:
`outputs{1} = vl_nnnormalizelp(inputs{1}, 'p', 2, 'epsilon', 1e-6) ;`
I hope this solves your problems.

We are working on an update of our library and we will make it compatible with matconvnet-beta25 in the next release. Thank you.

**Comment by GrumpyZhou** [comment]
Hi @filipradenovic ,

Thanks for your quick reply!  I also found this solution yesterday~ This is exactly the solution. 
`outputs{1} = vl_nnnormalizelp(inputs{1}, 'p', 2, 'epsilon', 1e-6) ;`
